# Generated by Django 5.1.7 on 2025-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("done", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(null=True)),
                ("date_completed", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
