# Generated by Django 4.2.5 on 2025-03-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
